import { Square, Card } from './types';

export const squares: Omit<Square, 'id'>[] = [
    { name: "GO", type: 'go', houses: 0, mortgaged: false },
    { name: "Mediterranean Avenue", type: 'property', price: 60, rent: [2, 10, 30, 90, 160, 250], group: 'brown', houseCost: 50, houses: 0, mortgaged: false },
    { name: "Community Chest", type: 'community-chest', houses: 0, mortgaged: false },
    { name: "Baltic Avenue", type: 'property', price: 60, rent: [4, 20, 60, 180, 320, 450], group: 'brown', houseCost: 50, houses: 0, mortgaged: false },
    { name: "Income Tax", type: 'tax', houses: 0, mortgaged: false },
    { name: "Reading Railroad", type: 'railroad', price: 200, rent: [25, 50, 100, 200], group: 'railroad', houses: 0, mortgaged: false },
    { name: "Oriental Avenue", type: 'property', price: 100, rent: [6, 30, 90, 270, 400, 550], group: 'light-blue', houseCost: 50, houses: 0, mortgaged: false },
    { name: "Chance", type: 'chance', houses: 0, mortgaged: false },
    { name: "Vermont Avenue", type: 'property', price: 100, rent: [6, 30, 90, 270, 400, 550], group: 'light-blue', houseCost: 50, houses: 0, mortgaged: false },
    { name: "Connecticut Avenue", type: 'property', price: 120, rent: [8, 40, 100, 300, 450, 600], group: 'light-blue', houseCost: 50, houses: 0, mortgaged: false },
    { name: "Just Visiting", type: 'jail', houses: 0, mortgaged: false },
    { name: "St. Charles Place", type: 'property', price: 140, rent: [10, 50, 150, 450, 625, 750], group: 'pink', houseCost: 100, houses: 0, mortgaged: false },
    { name: "Electric Company", type: 'utility', price: 150, group: 'utility', houses: 0, mortgaged: false },
    { name: "States Avenue", type: 'property', price: 140, rent: [10, 50, 150, 450, 625, 750], group: 'pink', houseCost: 100, houses: 0, mortgaged: false },
    { name: "Virginia Avenue", type: 'property', price: 160, rent: [12, 60, 180, 500, 700, 900], group: 'pink', houseCost: 100, houses: 0, mortgaged: false },
    { name: "Pennsylvania Railroad", type: 'railroad', price: 200, rent: [25, 50, 100, 200], group: 'railroad', houses: 0, mortgaged: false },
    { name: "St. James Place", type: 'property', price: 180, rent: [14, 70, 200, 550, 750, 950], group: 'orange', houseCost: 100, houses: 0, mortgaged: false },
    { name: "Community Chest", type: 'community-chest', houses: 0, mortgaged: false },
    { name: "Tennessee Avenue", type: 'property', price: 180, rent: [14, 70, 200, 550, 750, 950], group: 'orange', houseCost: 100, houses: 0, mortgaged: false },
    { name: "New York Avenue", type: 'property', price: 200, rent: [16, 80, 220, 600, 800, 1000], group: 'orange', houseCost: 100, houses: 0, mortgaged: false },
    { name: "Free Parking", type: 'free-parking', houses: 0, mortgaged: false },
    { name: "Kentucky Avenue", type: 'property', price: 220, rent: [18, 90, 250, 700, 875, 1050], group: 'red', houseCost: 150, houses: 0, mortgaged: false },
    { name: "Chance", type: 'chance', houses: 0, mortgaged: false },
    { name: "Indiana Avenue", type: 'property', price: 220, rent: [18, 90, 250, 700, 875, 1050], group: 'red', houseCost: 150, houses: 0, mortgaged: false },
    { name: "Illinois Avenue", type: 'property', price: 240, rent: [20, 100, 300, 750, 925, 1100], group: 'red', houseCost: 150, houses: 0, mortgaged: false },
    { name: "B. & O. Railroad", type: 'railroad', price: 200, rent: [25, 50, 100, 200], group: 'railroad', houses: 0, mortgaged: false },
    { name: "Atlantic Avenue", type: 'property', price: 260, rent: [22, 110, 330, 800, 975, 1150], group: 'yellow', houseCost: 150, houses: 0, mortgaged: false },
    { name: "Ventnor Avenue", type: 'property', price: 260, rent: [22, 110, 330, 800, 975, 1150], group: 'yellow', houseCost: 150, houses: 0, mortgaged: false },
    { name: "Water Works", type: 'utility', price: 150, group: 'utility', houses: 0, mortgaged: false },
    { name: "Marvin Gardens", type: 'property', price: 280, rent: [24, 120, 360, 850, 1025, 1200], group: 'yellow', houseCost: 150, houses: 0, mortgaged: false },
    { name: "Go To Jail", type: 'go-to-jail', houses: 0, mortgaged: false },
    { name: "Pacific Avenue", type: 'property', price: 300, rent: [26, 130, 390, 900, 1100, 1275], group: 'green', houseCost: 200, houses: 0, mortgaged: false },
    { name: "North Carolina Avenue", type: 'property', price: 300, rent: [26, 130, 390, 900, 1100, 1275], group: 'green', houseCost: 200, houses: 0, mortgaged: false },
    { name: "Community Chest", type: 'community-chest', houses: 0, mortgaged: false },
    { name: "Pennsylvania Avenue", type: 'property', price: 320, rent: [28, 150, 450, 1000, 1200, 1400], group: 'green', houseCost: 200, houses: 0, mortgaged: false },
    { name: "Short Line", type: 'railroad', price: 200, rent: [25, 50, 100, 200], group: 'railroad', houses: 0, mortgaged: false },
    { name: "Chance", type: 'chance', houses: 0, mortgaged: false },
    { name: "Park Place", type: 'property', price: 350, rent: [35, 175, 500, 1100, 1300, 1500], group: 'dark-blue', houseCost: 200, houses: 0, mortgaged: false },
    { name: "Luxury Tax", type: 'tax', houses: 0, mortgaged: false },
    { name: "Boardwalk", type: 'property', price: 400, rent: [50, 200, 600, 1400, 1700, 2000], group: 'dark-blue', houseCost: 200, houses: 0, mortgaged: false },
];

export const communityChestCards: Omit<Card, 'id' | 'deck'>[] = [
    { text: "Get out of Jail, Free.", action: 'get-out-of-jail-free' },
    { text: "You have won second prize in a beauty contest. Collect $10.", action: 'collect', value: 10 },
    { text: "From sale of stock, you get $50.", action: 'collect', value: 50 },
    { text: "Life insurance matures. Collect $100.", action: 'collect', value: 100 },
    { text: "Income tax refund. Collect $20.", action: 'collect', value: 20 },
    { text: "Holiday fund matures. Receive $100.", action: 'collect', value: 100 },
    { text: "You inherit $100.", action: 'collect', value: 100 },
    { text: "Receive $25 consultancy fee.", action: 'collect', value: 25 },
    { text: "Pay hospital fees of $100.", action: 'pay', value: 100 },
    { text: "Bank error in your favor. Collect $200.", action: 'collect', value: 200 },
    { text: "Pay school fees of $50.", action: 'pay', value: 50 },
    { text: "Doctor's fee. Pay $50.", action: 'pay', value: 50 },
    { text: "It is your birthday. Collect $10 from every player.", action: 'collect-from-all', value: 10 },
    { text: "Advance to \"GO\" (Collect $200).", action: 'advance', value: 0 },
    { text: "You are assessed for street repairs. $40 per house. $115 per hotel.", action: 'street-repairs', value: { house: 40, hotel: 115 } },
    { text: "Go to Jail. Go directly to Jail. Do not pass \"GO\". Do not collect $200.", action: 'go-to-jail' },
];

export const chanceCards: Omit<Card, 'id' | 'deck'>[] = [
    { text: "GET OUT OF JAIL FREE.", action: 'get-out-of-jail-free' },
    { text: "Make General Repairs on All Your Property. For each house pay $25. For each hotel $100.", action: 'street-repairs', value: { house: 25, hotel: 100 } },
    { text: "Speeding fine $15.", action: 'pay', value: 15 },
    { text: "You have been elected chairman of the board. Pay each player $50.", action: 'pay-all', value: 50 },
    { text: "Go back three spaces.", action: 'move-back', value: 3 },
    { text: "ADVANCE TO THE NEAREST UTILITY.", action: 'advance-to-nearest', value: 'utility' },
    { text: "Bank pays you dividend of $50.", action: 'collect', value: 50 },
    { text: "ADVANCE TO THE NEAREST RAILROAD.", action: 'advance-to-nearest', value: 'railroad' },
    { text: "Pay poor tax of $15.", action: 'pay', value: 15 },
    { text: "Take a trip to Reading Rail Road.", action: 'advance', value: 5 },
    { text: "ADVANCE to Boardwalk.", action: 'advance', value: 39 },
    { text: "ADVANCE to Illinois Avenue.", action: 'advance', value: 24 },
    { text: "Your building loan matures. Collect $150.", action: 'collect', value: 150 },
    { text: "ADVANCE TO THE NEAREST RAILROAD.", action: 'advance-to-nearest', value: 'railroad' },
    { text: "ADVANCE to St. Charles Place.", action: 'advance', value: 11 },
    { text: "Go to Jail. Go Directly to Jail.", action: 'go-to-jail' },
];
